resource_group_name = "vmcreation"
location            = "eastus"
vnet_name = "vmvnet"
vnet_space = "10.0.0.0/16"
subnet = "subnet"
subnet_space = "10.0.2.0/24"
vm_name = "bsltest"
dynamic = "Dynamic"
